# Tasks specifically related to AMY integration.

- name: install pexpect package systemwide so Ansible can use it
  pip: name=pexpect version=4.2.0
  sudo: yes

# Creating a Django user account will fail if a user with that same
# name already exists, so we ignore errors.
- name: create AMY superuser
  django_manage: command="createsuperuser  --noinput --username {{ amy_username }} --email {{ admin_email }}"
                 app_path={{ project_folder_root }}
                 settings=conf_site.settings.{{ environment_type }}
                 virtualenv={{ virtualenv_root }}/current
  ignore_errors: yes

# We can't use the django_manage Ansible module because the
# django management command "changepassword" does not support
# programatically changing passwords. See
# <https://code.djangoproject.com/ticket/18897>.
- name: change AMY superuser password
  expect:
    chdir: "{{ project_folder_root }}"
    command: "/bin/bash -c 'DJANGO_SETTINGS_MODULE=conf_site.settings.{{ environment_type }} {{ virtualenv_root }}/current/bin/python ./manage.py changepassword {{ amy_username }}'"
    responses:
      (?i)password: "{{ amy_password }}"
